FROM alpine:latest AS builder
COPY ../ /work
ARG GOOS
ARG GOARCH
RUN apk update \
    && apk add --no-cache go \
    && mkdir /data \
    && cd /work \
    && CGO_ENABLED=0 GOOS=${GOOS} GOARCH=${GOARCH} go build -ldflags "-w -extldflags '-static'" -o "/data/fastplate"

FROM alpine:latest
COPY --from=builder "/data/fastplate" /data/
ENTRYPOINT ["/data/fastplate"]