FROM alpine:latest AS builder
COPY ../ /work
ARG GOOS
ARG GOARCH
RUN apk update \
    && apk add go \
    && mkdir /data \
    && cd /work \
    && CGO_ENABLED=0 GOOS=${GOOS} GOARCH=${GOARCH} go build -ldflags "-w -extldflags '-static'" -o "/data/yatt"

FROM alpine:latest
COPY --from=builder "/data/yatt" /data/
WORKDIR /work
ENTRYPOINT ["/data/yatt"]